---
- name: Deploy EC2 instance
  hosts: localhost
  connection: local # using aws api
  gather_facts: False

  vars:
    region: eu-south-2 # Spain
    instance_type: t2.nano
    ami: ami-O70b208e993b59cea
    keypair: ansible_keypair #pem file
    subnetid: your-subnet-id

  tasks:
    - name: Create EC2 instance
      ec2_instance:
        key_name: "{{ keypair }}"
        security_group: default # security group name
        instance_type: "{{ instance_type }}"
        image_id: "{{ ami }}"
        wait: true
        region: "{{ region }}"
        count: 3 # deploys 3 ec2 instances
        instance_tags:
          Name: Ansible-EC2-Test
        vpc_subnet_id: "{{ subnetid }}"
        network:
          assign_public_ip: yes
      register: ec2

    - name: Show output
      debug:
        msg: "{{ ec2 }}"
